program: bbox/main.py
command:
  - ${env}
  - ${interpreter}
  - "-m"
  - bbox.main
  - ${args}

method: random

metric:
  name: Best validation metric
  goal: minimize

parameters:

  lr:
    distribution: categorical
    values: [0.001, 0.0001]

  optimizer:
    distribution: categorical
    values: ["Adam", "AdamW"]
  
  scheduler:
    value: "CosineAnnealingWarmRestarts"

  fm:
    distribution: categorical
    values: ["resnet", "transform"]
  
  epochs:
    value: 5

  bs:
    value:  16

  tr:
    value: 5

  sweep:
    value: True