program: pose2/main.py
command:
  - ${env}
  - ${interpreter}
  - "-m"
  - pose2.main
  - ${args}

method: grid

metric:
  name: Best validation metric
  goal: minimize

parameters:

  lr:
    value: 0.001

  optimizer:
    value: "Adam"

  scheduler:
    value: "CosineAnnealingWarmRestarts"

  mod:
    distribution: categorical
    values: ["bb8_1", "bb8_2", "bb8_3"]

  epochs:
    value: 40

  bs:
    value: 64

  sweep:
    value: True
