program: 2dBox/main.py
command:
  - ${env}
  - ${interpreter}
  - "-m"
  - 2dBox.main
  - ${args}

method: random

metric:
  name: Best validation metric
  goal: minimize

parameters:

  lr:
    distribution: categorical
    values: [0.001, 0.0001]

  optimizer:
    distribution: categorical
    values: ["Adam", "AdamW", "SGD", "RMSprop"]
  
  scheduler:
    distribution: categorical
    values: ["CosineAnnealingWarmRestarts", "ReduceLROnPlateau", "None"]
  
  epochs:
    value: 3

  bs:
    distribution: categorical
    values: [16, 32, 64]

  tr:
    distribution: int_uniform
    min: 0
    max: 5