
# Model conf
backbone : "setup_test"
head : "custom"
nr_output_channels: 16
input_channels : 4
input_folder : "../Linemod"

# Optimizer
optimizer : "Adam"
scheduler : "warmup"

# Hyperparams
learning_rate : 0.01
batch_size : 64
epochs : 10
dropout : 0.05

#Other configs
load_data : False
data_folder : "dataset/"
