
# Model conf
backbone : "test_backbone"
head : "test_head"
output_channels: 16
input_channels : 4

# Optimizer
optimizer : "Adam"
scheduler : "ReduceLROnPlateau"

# Hyperparams
learning_rate : 0.0001
batch_size : 16
epochs : 10
dropout : 0.05

#Other configs
data_dir : "datasets/"
train_% : 0.6
val_% : 0.2
test_% : 0.2
