program: pose/main.py
method: random

metric:
  name: Best validation metric
  goal: minimize

parameters:

  lr:
    distribution: categorical
    values: [0.01, 0.001, 0.0001]

  optimizer:
    distribution: categorical
    #values: ["Adam", "AdamW", "SGD", "RMSprop", "Adagrad"]
    values: ["Adam", "AdamW"]

  scheduler:
    distribution: categorical
    values: ["CosineAnnealingWarmRestarts", "ReduceLROnPlateau", "None"]
  
  epochs:
    value: 10

  bs:
    distribution: categorical
    values: [8, 16, 32]

  mod:
    distribution: categorical
    values: ["res", "eff"]

